name: Java CI with Gradle

on:
  push:
    branches: [ "release" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    ## create application.properties
    - name: make application.properties
      run: |
        ## create application.properties
        cd ./src/main/resources

        # application.properties 파일 생성
        touch ./application.properties

        # GitHub-Actions 에서 설정한 값을 application.properties 파일에 쓰기
        echo "${{ secrets.APPLICATION }}" >> ./application.properties
      shell: bash

    ## gradle build
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew clean build


    ## 웹 이미지 빌드 및 도커허브에 push
    - name: web docker build and push
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/asac-5th-b:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/asac-5th-b:latest

    ## docker compose up
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
          sudo docker-compose down -v
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/asac-5th-b:latest
          sudo docker-compose up -d
          sudo docker image prune -a -f
